<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\StaffConteroller.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\css\NewFile.txt" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Controllers\NewFile.txt" />
    <None Remove="Controllers\staffC" />
    <None Remove="Models\NewFile.txt" />
    <None Remove="Views\Admin\Index.html" />
    <None Remove="Views\Admin\NewFile.txt" />
    <None Remove="Views\Customer\NewFile.txt" />
    <None Remove="Views\Gameslot\NewFile.txt" />
    <None Remove="Views\Home\NewFile.txt" />
    <None Remove="Views\Shared\NewFile.txt" />
    <None Remove="Views\Shared\S" />
    <None Remove="Views\SlotBooking\NewFile.txt" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="2.2.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
    <PackageReference Include="Razorpay" Version="3.1.4" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
  </ItemGroup>

</Project>
